In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
from sklearn.datasets import load_boston

# MULTI LINEAR REGRESSION

In [31]:
X=load_boston()
data=pd.DataFrame(X.data,columns=X.feature_names)
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [32]:
data['target']=X.target

In [33]:
x=data.iloc[:,:-1]
y=data[['target']]

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [35]:
from sklearn.linear_model import LinearRegression
A=LinearRegression()
model=A.fit(x_train,y_train)

In [36]:
pred=model.predict(x_test)
pred_train=model.predict(x_train)

In [37]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
MSE=mean_squared_error(y_test,pred)
MSE_TRAIN=mean_squared_error(y_train,pred_train)
MAE=mean_absolute_error(y_test,pred)
MAE_TRAIN=mean_absolute_error(y_train,pred_train)

In [38]:
RMSE=np.sqrt(MSE)
RMSE_TRAIN=np.sqrt(MSE_TRAIN)

R2=model.score(x_test,y_test)
R2_TRAIN=model.score(x_train,y_train)

In [39]:
MSE,MSE_TRAIN,MAE,MAE_TRAIN,RMSE,RMSE_TRAIN,R2,R2_TRAIN

(17.822599644370033,
 23.274039808492184,
 3.2054553877960164,
 3.4087070811829188,
 4.22168208707975,
 4.824317548471719,
 0.7188989913559678,
 0.7400838005768904)

# POLYNOMIAL REGRESSION

In [40]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(data.iloc[:,:-1])
xp=pd.DataFrame(x_poly)
xp

,0,1,2,3,4,5,6,7,8,9,...,95,96,97,98,99,100,101,102,103,104
0,1.0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,...,87616.0,4528.8,117482.40,1474.08,234.09,6072.570,76.194,157529.6100,1976.5620,24.8004
1,1.0,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,...,58564.0,4307.6,96049.80,2211.88,316.84,7064.820,162.692,157529.6100,3627.6660,83.5396
2,1.0,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,...,58564.0,4307.6,95064.86,975.26,316.84,6992.374,71.734,154315.4089,1583.1049,16.2409
3,1.0,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,...,49284.0,4151.4,87607.86,652.68,349.69,7379.581,54.978,155732.8369,1160.2122,8.6436
4,1.0,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,...,49284.0,4151.4,88111.80,1183.26,349.69,7422.030,99.671,157529.6100,2115.4770,28.4089
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,1.0,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,...,74529.0,5733.0,107013.27,2639.91,441.00,8231.790,203.070,153656.1601,3790.5433,93.5089
502,1.0,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,...,74529.0,5733.0,108353.70,2478.84,441.00,8334.900,190.680,157529.6100,3603.8520,82.4464
503,1.0,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,...,74529.0,5733.0,108353.70,1539.72,441.00,8334.900,118.440,157529.6100,2238.5160,31.8096
504,1.0,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,...,74529.0,5733.0,107411.85,1769.04,441.00,8262.450,136.080,154802.9025,2549.5560,41.9904
505,1.0,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,...,74529.0,5733.0,108353.70,2151.24,441.00,8334.900,165.480,157529.6100,3127.5720,62.0944

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(xp,y,test_size=0.2)

In [42]:
from sklearn.linear_model import LinearRegression
A=LinearRegression()
model1=A.fit(x_train,y_train)

In [43]:
pred1=model1.predict(x_test)

pred_train1=model1.predict(x_train)

In [44]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
MSE1=mean_squared_error(y_test,pred1)
MSE_TRAIN1=mean_squared_error(y_train,pred_train1)
MAE1=mean_absolute_error(y_test,pred1)
MAE_TRAIN1=mean_absolute_error(y_train,pred_train1)

In [45]:
RMSE1=np.sqrt(MSE1)
RMSE_TRAIN1=np.sqrt(MSE_TRAIN1)

R21=model1.score(x_test,y_test)
R2_TRAIN1=model1.score(x_train,y_train)

In [46]:
MSE1,MSE_TRAIN1,MAE1,MAE_TRAIN1,RMSE1,RMSE_TRAIN1,R21,R2_TRAIN1

(10.98755029317596,
 5.622807816810459,
 2.49315544027325,
 1.704849930190633,
 3.314747395077936,
 2.3712460472946413,
 0.8478006729764237,
 0.9355762742309239)

In [47]:
from sklearn.preprocessing import PolynomialFeatures
p5=PolynomialFeatures(degree=5)
polymodel=p5.fit_transform(data.iloc[:,:-1])
poly5=pd.DataFrame(polymodel)

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(poly5,y)

In [49]:
from sklearn.linear_model import LinearRegression
C=LinearRegression()
model2=C.fit(x_train,y_train)

In [50]:
pred2=model2.predict(x_test)
pred_TRAIN2=model2.predict(x_train)

In [51]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [52]:
MSE2=mean_squared_error(y_test,pred2)
MSE_TRAIN2=mean_squared_error(y_train,pred_TRAIN2)

In [53]:
MAE2=mean_absolute_error(y_test,pred2)
MAE_TRAIN2=mean_absolute_error(y_train,pred_TRAIN2)

In [54]:
RMSE2=np.sqrt(MSE2)
RMSE_TRAIN2=np.sqrt(MSE_TRAIN2)

In [55]:
R22=model2.score(x_test,y_test)
R2_TRAIN2=model2.score(x_train,y_train)

In [56]:
MSE2,MSE_TRAIN2,MAE2,MAE_TRAIN2,RMSE2,RMSE_TRAIN2,R22,R2_TRAIN2

(358349.82980825566,
 3.3996864864085625e-19,
 75.73515168252986,
 4.53027132078842e-10,
 598.623278705611,
 5.830683052960916e-10,
 -4720.115407837496,
 1.0)

In [57]:
from sklearn.preprocessing import PolynomialFeatures
p5=PolynomialFeatures(degree=5)
polymodel=p5.fit_transform(data.iloc[:,:-1])
poly5=pd.DataFrame(polymodel)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(poly5,y)

from sklearn.linear_model import LinearRegression
C=LinearRegression()
model3=C.fit(x_train,y_train)

pred3=model3.predict(x_test)
pred_TRAIN3=model3.predict(x_train)

from sklearn.metrics import mean_absolute_error,mean_squared_error

MSE3=mean_squared_error(y_test,pred3)
MSE_TRAIN3=mean_squared_error(y_train,pred_TRAIN3)

MAE3=mean_absolute_error(y_test,pred3)
MAE_TRAIN3=mean_absolute_error(y_train,pred_TRAIN3)

RMSE3=np.sqrt(MSE3)
RMSE_TRAIN3=np.sqrt(MSE_TRAIN3)

R23=model3.score(x_test,y_test)
R2_TRAIN3=model3.score(x_train,y_train)

In [58]:
MSE3,MSE_TRAIN3,MAE3,MAE_TRAIN3,RMSE3,RMSE_TRAIN3,R23,R2_TRAIN3

(100748.4045864245,
 1.8215149711634495e-20,
 74.64802798695032,
 1.0870955850545561e-10,
 317.40889178853274,
 1.3496351251962323e-10,
 -1619.5146024177918,
 1.0)

In [92]:


O=[MSE,MAE,RMSE,R2,MSE_TRAIN,MAE_TRAIN,RMSE_TRAIN,R2_TRAIN]

P=[MSE1,MAE1,RMSE1,R21,MSE_TRAIN1,MAE_TRAIN1,RMSE_TRAIN1,R2_TRAIN1]

Q=[MSE2,MAE2,RMSE2,R22,MSE_TRAIN2,MAE_TRAIN2,RMSE_TRAIN2,R2_TRAIN2]

R=[MSE3,MAE3,RMSE3,R23,MSE_TRAIN3,MAE_TRAIN3,RMSE_TRAIN3,R2_TRAIN3]

In [93]:
RESULT=pd.DataFrame(index=['','TEST','','','','','TRAIN',''],columns=['','MLR','PLR2','PLR5','PLR10'])
RESULT['']=['MSE','MAE','RMSE','R SQUARE','MSE','MAE','RMSE','R SQUARE']
RESULT['MLR']=O
RESULT['PLR2']=P
RESULT['PLR5']=Q
RESULT['PLR10']=R

In [94]:
RESULT

                       MLR       PLR2          PLR5         PLR10
            MSE  17.822600  10.987550  3.583498e+05  1.007484e+05
TEST        MAE   3.205455   2.493155  7.573515e+01  7.464803e+01
           RMSE   4.221682   3.314747  5.986233e+02  3.174089e+02
       R SQUARE   0.718899   0.847801 -4.720115e+03 -1.619515e+03
            MSE  23.274040   5.622808  3.399686e-19  1.821515e-20
            MAE   3.408707   1.704850  4.530271e-10  1.087096e-10
TRAIN      RMSE   4.824318   2.371246  5.830683e-10  1.349635e-10
       R SQUARE   0.740084   0.935576  1.000000e+00  1.000000e+00

In [76]:
O=[MSE,MAE,RMSE,R2,MSE_TRAIN,MAE_TRAIN,RMSE_TRAIN,R2_TRAIN]

In [77]:
P=[MSE1,MAE1,RMSE1,R21,MSE_TRAIN1,MAE_TRAIN1,RMSE_TRAIN1,R2_TRAIN1]

In [78]:
Q=[MSE2,MAE2,RMSE2,R22,MSE_TRAIN2,MAE_TRAIN2,RMSE_TRAIN2,R2_TRAIN2]

In [79]:
R=[MSE3,MAE3,RMSE3,R23,MSE_TRAIN3,MAE_TRAIN3,RMSE_TRAIN3,R2_TRAIN3]